title: Next Code
baseurl: ""
url: ""
github_username:  gapry
markdown: kramdown
theme: jekyll-theme-minimal
languages: ["en"]
exclude_from_localizations: ["javascript", "images", "css"]
plugins:
 - jekyll-feed
